const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const {JSDOM}=require("./work/v02-tests/node_modules/jsdom");
const M=require("./dist/course-model"),C=require("./dist/calendar"),I=require("./dist/course-import");
const monday="2026-09-07";
const c=M.course({name:"数据结构"});
c.sessions=[M.session({day:1,start:"08:00",end:"09:40",weeks:"1-4",parity:"odd"}),M.session({day:1,start:"14:00",end:"15:40",weeks:"1-4",parity:"odd"}),M.session({day:3,start:"10:00",end:"11:40",weeks:"1-4",parity:"even"})];
assert.throws(()=>M.exportEvents([c],monday),/待核对/);
c.needsReview=false;const ev=M.exportEvents([c],monday);
assert.equal(ev.length,6);assert.equal(new Set(ev.map(x=>x.id+"-"+x.date)).size,6);
assert.equal((C.ics(ev).match(/UID:/g)||[]).length,6);
assert.throws(()=>M.validate({...c,sessions:[M.session({day:1})]},monday),/有效时间/);
const raw="课程：数据结构\n教师：张老师\n教室：教五201\n周一 08:00-09:40\n周三 10:00-11:40\n周次：1-16\n单周";
const parsed=I.parseText(raw);
assert.equal(parsed.length,1);assert.equal(parsed[0].name,"数据结构");assert.equal(parsed[0].teacher,"张老师");
assert.deepEqual(parsed[0].sessions.map(s=>[s.day,s.start,s.end,s.parity,s.weeks]),[[1,"08:00","09:40","odd","1-16"],[3,"10:00","11:40","odd","1-16"]]);
assert.equal(I.parseText("课程：高等数学\n星期二\n第3-4节")[0].sessions[0].start,"");
assert.equal(I.parseText("课程：大学英语")[0].sessions.length,0);
const twice=M.mergeDrafts(M.mergeDrafts([],parsed),parsed);
assert.equal(twice.length,1);assert.equal(twice[0].sessions.length,2);assert.ok(twice[0].needsReview);
const diff=M.mergeDrafts(twice,[{...parsed[0],teacher:"李老师"}]);assert.equal(diff.length,2);
const w=(text,x,y)=>({text,bbox:{x0:x,y0:y,x1:x+90,y1:y+20}});
const grid={text:"",blocks:[{paragraphs:[{lines:[{words:[w("星期一",100,10),w("星期三",400,10),w("数据结构",100,60),w("08:00-09:40",100,90),w("1-16周",100,120),w("高等数学",400,60),w("10:00-11:40",400,90),w("1-8周",400,120)]}]}]}]};
const gridResult=I.parseOcr(grid);assert.equal(gridResult.gridDetected,true);assert.equal(gridResult.drafts.length,2);assert.equal(gridResult.drafts[1].sessions[0].day,3);
const dom=new JSDOM(fs.readFileSync(path.join(__dirname,"dist/index.html"),"utf8"),{url:"https://test.invalid",runScripts:"outside-only"});
const win=dom.window,d=win.document;win.TextEncoder=TextEncoder;win.Blob=Blob;let downloaded=null;
win.URL.createObjectURL=b=>{downloaded=b;return "blob:test";};win.URL.revokeObjectURL=()=>{};win.HTMLAnchorElement.prototype.click=function(){};win.confirm=()=>true;
for(const file of ["calendar.js","course-model.js","course-import.js","ocr.js","app.js"])win.eval(fs.readFileSync(path.join(__dirname,"dist",file),"utf8"));
const fill=(id,value)=>{const n=d.getElementById(id);n.value=value;n.dispatchEvent(new win.Event(n.tagName==="SELECT"?"change":"input",{bubbles:true}));};
const click=id=>d.getElementById(id).click();
const setLabel=(label,value)=>{const n=d.querySelector('[aria-label="'+label+'"]');assert.ok(n,label);n.value=value;n.dispatchEvent(new win.Event(n.tagName==="SELECT"?"change":"input",{bubbles:true}));};
fill("registerName","数据结构");d.getElementById("registerForm").dispatchEvent(new win.Event("submit",{bubbles:true,cancelable:true}));
d.querySelector('[aria-label="周一有课"]').click();d.querySelector('[aria-label="周三有课"]').click();
setLabel("周一时段1开始时间","08:00");setLabel("周一时段1结束时间","09:40");setLabel("周一时段1周数","1-4");setLabel("周一时段1单双周","odd");
setLabel("周三时段1开始时间","10:00");setLabel("周三时段1结束时间","11:40");setLabel("周三时段1周数","1-4");setLabel("周三时段1单双周","even");
click("confirmCourse");assert.equal(d.getElementById("count").textContent,"4 次已确认课程");assert.equal(d.getElementById("download").disabled,false);
d.querySelector(".day-group button").click();
setLabel("周一时段2开始时间","14:00");setLabel("周一时段2结束时间","15:40");setLabel("周一时段2周数","1-4");
click("confirmCourse");assert.equal(d.getElementById("count").textContent,"8 次已确认课程");
fill("editName","数据结构（实验）");assert.equal(d.getElementById("download").disabled,true);click("confirmCourse");assert.ok(d.getElementById("events").textContent.includes("数据结构（实验）"));
fill("registerName","待补课");d.getElementById("registerForm").dispatchEvent(new win.Event("submit",{cancelable:true}));assert.ok(d.getElementById("download").disabled);
d.getElementById("download").onclick();assert.equal(downloaded,null);
click("deleteCourse");assert.equal(d.querySelectorAll(".course-choice").length,1);
fill("rawText","课程：数据结构（实验）\n周五 10:00-11:40\n周次：1-4");click("parseText");click("importCandidates");
assert.equal(d.querySelectorAll(".course-choice").length,1);assert.equal(d.querySelectorAll(".session").length,4);assert.ok(d.getElementById("download").disabled);
click("confirmCourse");assert.equal(d.getElementById("count").textContent,"12 次已确认课程");
fill("rawText","课程：数据结构（实验）\n周五 10:00-11:40\n周次：1-4");click("parseText");click("importCandidates");assert.equal(d.querySelectorAll(".session").length,4);click("confirmCourse");click("download");
(async()=>{
 const text=await downloaded.text();assert.equal((text.match(/BEGIN:VEVENT/g)||[]).length,12);
 let terminated=0;
 win.Tesseract={createWorker:async()=>({setParameters:async()=>{},recognize:async()=>({data:{text:"课程：英语"}}),terminate:async()=>{terminated++;}})};
 assert.equal((await win.CourseOcr.recognize("fake")).text,"课程：英语");assert.equal(terminated,1);
 win.Tesseract={createWorker:async()=>({setParameters:async()=>{},recognize:()=>new Promise(()=>{}),terminate:async()=>{terminated++;}})};
 const pending=win.CourseOcr.recognize("fake");setTimeout(()=>win.CourseOcr.cancel(),10);await assert.rejects(pending,/已取消/);
 assert.equal(d.querySelectorAll(".course-choice").length,1);
 dom.window.close();
 console.log("v0.2通过：多日、同日多时段、独立单双周、唯一UID、待核对导出拦截、识图解析与合并、表单全流程、下载事件数、OCR取消与资源释放。");
})().catch(e=>{dom.window.close();console.error(e);process.exitCode=1;});

assert.deepEqual(I.parseText("课程:数据结构\n周一 08:00-09:40 单周 周三 10:00-11:40 双周")[0].sessions.map(s=>[s.day,s.start,s.parity]),[[1,"08:00","odd"],[3,"10:00","even"]]);
assert.deepEqual(I.parseText("课程:数据结构\n周一 08:00-09:40 单周\n周三 第3-4节")[0].sessions.map(s=>[s.day,s.start,s.parity]),[[1,"08:00","odd"],[3,"","all"]]);
